version: '3'

services:
  web:
    build:
      context: .
      dockerfile: compose/web/Dockerfile
    volumes:
      - .:/app
      - ~/.npm-global:/app/.npm-global
      - ~/.config/yarn:/app/.config/yarn
      - ./node_modules:/app/node_modules
      - cache:/app/cache
      - public:/app/public
      - yarn_cache:/usr/local/share/.cache/yarn/v4
    ports:
      - '12800:12800'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      GITHUB_TOKEN: '36b2c5ea7e5760758f3ae33ca612e0f985ba8320'
      DOCKER: 'true'
      NODE_OPTIONS: '--max_old_space_size=12000'
    command: ['yarn', 'develop', '--host', '0.0.0.0', '--port', '12800']

volumes:
  node_modules: {}
  cache: {}
  public: {}
  yarn_cache: {}
